services:
  api:
    build: .
    container_name: urabot-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/urabot
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    container_name: urabot-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
